spring:
  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  graphql:
    graphiql:
      enabled: true
    schema:
      printer:
        enabled: true
      inspection:
        enabled: true